@LacunaDevOps.Site_HostAddress = https://localhost:44324

POST {{LacunaDevOps.Site_HostAddress}}/api/ingredients
Content-Type: application/json

{
  "name": "Sugar",
  "standardUnitOfMeasure": 0
}

###
